server:
  port: 8762
  
spring:
  application:
    name: Eureka-Server
    
eureka:
  instance:
    hostname: peer2
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

    
