#eureka.clinet.serviceUrl.defaultZone=http\://localhost\:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: hello-service
       #开启重试机制
  cloud: 
    loadbalancer:
      retry:
        enabled: true
    
eureka:
  clinet:
    serviceUrl:
      defaultZone: http\://peer1\:8761/eureka/,http\://peer2\:8762/eureka/
   #断路器的超时时间要超过ribbon的超时时间，否则不会触发重试   
hystrix :
  command: 
    default:
      execution: 
        isolation:
          thread:
            timeoutInMilliseconds: 1000

hello-service: 
  ribbon:
    #请求连接超时时间 
    Connectimeout: 250
    #请求处理的超时时间
    ReadTimeOut: 1000
    #是否对所有的操作进行重试
    OkToRetryOnAllOperations: true
    #切换实例重试下个服务的次数
    MaxAutoRetriesNextServer: 2
    #对当前实例进行重试
    MaxAutoResties: 1
    