#server:
#  port: 8762
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-server1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true 
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/ 
---
spring:
  application:
    name: eureka-server2
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: true 
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

 
      